BitirmeProjesi/Controllers/AuthorizationController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BitirmeProjesi.Controllers
{
    public class AuthorizationController : Controller
    {
        AdminManager adminmanager = new AdminManager(new EfAdminDal());
        public ActionResult Index()
        {
            var adminvalues = adminmanager.GetList();
            return View(adminvalues);
        }
        [HttpGet]
        public ActionResult AddAdmin() 
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddAdmin(Admin p)
        {
            adminmanager.AdminAdd(p);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult EditAdmin(int id)
        {
            var adminvalue = adminmanager.GetByID(id);
            return View(adminvalue);
        }
        [HttpPost]
        public ActionResult EditAdmin(Admin p)
        {

            adminmanager.AdminUpdate(p);
            return RedirectToAction("Index");
        }
        public ActionResult DeleteAdmin(int id)
        {
            var adminvalue = adminmanager.GetByID(id);
            adminmanager.AdminDelete(adminvalue);
            return RedirectToAction("Index");
        }
    }
}

BitirmeProjesi/Views/Authorization/AddAdmin.cshtml
@model EntityLayer.Concrete.Admin
@{
    ViewBag.Title = "AddAdmin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Yeni admin ekleme sayfası</h1>
<br />
@using (Html.BeginForm("AddAdmin", "Authorization", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Admin Kullanıcı Adı")
        @Html.TextBoxFor(x => x.AdminUserName, new { @class = "form-control" })
        <br /> 
        @Html.Label("Şifreyi giriniz")
        @Html.TextBoxFor(x => x.AdminPassword, new { @class = "form-control" })
        <br /> 
        @Html.Label("Rolü Seçiniz")
        @Html.TextBoxFor(x => x.AdminRole, new { @class = "form-control" })
        <br /> 
        <button>Kaydet</button>
    </div>
}

BitirmeProjesi/Views/Authorization/EditAdmin.cshtml
@model EntityLayer.Concrete.Admin
@{
    ViewBag.Title = "EditAdmin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Admin Güncelleme Sayfası</h2>

@using (Html.BeginForm("EditAdmin", "Authorization", FormMethod.Post))
{
    <div class="form-group">

        @Html.HiddenFor(x => x.AdminID)
        <br />

        @Html.Label("Admin Kullanıcı Adı")
        @Html.TextBoxFor(x => x.AdminUserName)
        <br />
        @Html.Label("Şifre")
        @Html.TextAreaFor(x => x.AdminPassword)
        <br />
        @Html.Label("Admin Rolü")
        @Html.TextAreaFor(x => x.AdminRole, new { @class = "form-control" })
        <br />
        <button class="btn btn-success">Güncelle</button>
    </div>
}

BitirmeProjesi/Views/Authorization/Index.cshtml
@using EntityLayer.Concrete
@model List<Admin>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Kullanıcı Mail</th>
        <th>Yetki</th>
        <th>Status</th>
        <th>Pasif Yap</th>
        <th>Yetkisini Değiştir</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <th>@item.AdminID</th>
            <td>@item.AdminUserName</td>
            <td>@item.AdminRole</td>
            <td>Aktif</td>
            <td><a href="/Authorization/Index/@item.AdminID" class="btn btn-danger">Pasif Yap</a></td>
            <td><a href="/Authorization/EditAdmin/@item.AdminID" class="btn btn-warning">Yetkisini Değiştir</a></td>
        </tr>
    }

</table>

<a href="/Authorization/AddAdmin/" class="btn btn-info">Yeni Admin Tanımla</a>